// Compiles the source stylesheets into dist/ by inlining every @import.
// No dependencies: plain Node, so it also runs when the package is installed from GitHub.
//   dist/styles.css      tokens + base            ("glazeos-design-system/styles")
//   dist/components.css  every component family  ("glazeos-design-system/components")
//   dist/glazeos.css     both, in order           ("glazeos-design-system")
//   dist/icons.mjs       the approved Lucide icons as SVG strings ("glazeos-design-system/icons"), from
//                        src/icons/icons.json and the pinned lucide-static devDependency
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const src = path.join(root, 'src/styles');
const dist = path.join(root, 'dist');
const { version } = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));

function inline(file, seen = new Set()) {
  const abs = path.resolve(file);
  if (seen.has(abs)) return '';
  seen.add(abs);
  const css = fs.readFileSync(abs, 'utf8');
  return css.replace(/@import\s+['"]([^'"]+)['"];?/g, (_, rel) => inline(path.join(path.dirname(abs), rel), seen));
}

const banner = (name) => `/*! glazeos-design-system v${version} — ${name} — built ${new Date().toISOString().slice(0, 10)} */\n`;
const styles = inline(path.join(src, 'index.css'));
const components = inline(path.join(src, 'components.css'));

fs.rmSync(dist, { recursive: true, force: true });
fs.mkdirSync(dist, { recursive: true });
fs.writeFileSync(path.join(dist, 'styles.css'), banner('tokens + base') + styles);
fs.writeFileSync(path.join(dist, 'components.css'), banner('components') + components);
fs.writeFileSync(path.join(dist, 'glazeos.css'), banner('everything') + styles + '\n' + components);

// ---- icons: src/icons/icons.json -> dist/icons.mjs (server-side SVG strings; nothing runs in the browser) ----
const lucideDir = path.join(root, 'node_modules/lucide-static');
const { icons: iconNames } = JSON.parse(fs.readFileSync(path.join(root, 'src/icons/icons.json'), 'utf8'));
const lucideVersion = JSON.parse(fs.readFileSync(path.join(lucideDir, 'package.json'), 'utf8')).version;
const lucideLicense = fs.readFileSync(path.join(lucideDir, 'LICENSE'), 'utf8').trim().replace(/\*\//g, '* /');
const iconBodies = Object.fromEntries(iconNames.map((name) => {
  const svg = fs.readFileSync(path.join(lucideDir, 'icons', `${name}.svg`), 'utf8');
  const body = svg.slice(svg.indexOf('>', svg.indexOf('<svg')) + 1, svg.lastIndexOf('</svg>')).replace(/\s+/g, ' ').replace(/\s*\/>/g, '/>').replace(/>\s+</g, '><').trim();
  return [name, body];
}));
const iconsModule = `/*! glazeos-design-system v${version} — icons (Lucide ${lucideVersion}) — built ${new Date().toISOString().slice(0, 10)}
 * Generated by scripts/build.mjs from src/icons/icons.json. Do not edit by hand: add a name there and rebuild.
 *
 * icon(name, { size, label, className }) returns an inline <svg> string, drawn in the text colour.
 *   size   'sm' (12px) | 'md' (14px, default) | 'lg' (20px); the matching .gos-icon--<size> class sets the line weight
 *   label  for an icon that carries meaning on its own: role="img" + aria-label. Without it the icon is aria-hidden.
 * An unknown name throws, so a typo fails the site's build instead of shipping a blank space.
 *
 * Icons: Lucide (https://lucide.dev), lucide-static ${lucideVersion}. Its licence, reproduced as it requires:
 *
${lucideLicense.split('\n').map((l) => ` * ${l}`.trimEnd()).join('\n')}
 */
export const ICONS = ${JSON.stringify(iconBodies, null, 2)};
export const ICON_NAMES = Object.keys(ICONS);
const SIZES = { sm: 12, md: 14, lg: 20 };
const WEIGHTS = { sm: 2.5, md: 2, lg: 1.75 }; // same as .gos-icon--<size> in icons.css, so it's right before the CSS loads too
const esc = (v) => String(v).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/"/g, '&quot;');
export function icon(name, { size = 'md', label, className = '' } = {}) {
  const body = ICONS[name];
  if (!body) throw new Error(\`[glazeos-design-system/icons] no icon "\${name}". Add it to src/icons/icons.json in the design system. Available: \${ICON_NAMES.join(', ')}\`);
  const px = SIZES[size];
  if (!px) throw new Error(\`[glazeos-design-system/icons] no size "\${size}" (sm, md or lg)\`);
  const a11y = label ? \`role="img" aria-label="\${esc(label)}"\` : 'aria-hidden="true"';
  return \`<svg class="gos-icon gos-icon--\${size}\${className ? \` \${esc(className)}\` : ''}" width="\${px}" height="\${px}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="\${WEIGHTS[size]}" stroke-linecap="round" stroke-linejoin="round" \${a11y} focusable="false">\${body}</svg>\`;
}
`;
fs.writeFileSync(path.join(dist, 'icons.mjs'), iconsModule);

for (const f of fs.readdirSync(dist)) {
  console.log(`dist/${f}  ${(fs.statSync(path.join(dist, f)).size / 1024).toFixed(1)} KB`);
}
